### ISSUE TITLE
Experimental parameter inquiry

### ISSUE THREAD

**Issue by ZeyuZhu0120** [bdi-lab/HyNT#1]
Hello author,
I have been studying your work recently, and I want to ask you some minor questions about the code.
I noticed you provided some checkpoints for training, but I wanted to train myself.
The default parameters provided in the train.py file are for the HN-WK data set, which works very well (and is basically consistent with the results in the paper). I wonder what the training parameters are for the other datasets HN-YG, HN-FB, HN-FB-S, etc. I notice that the readme gives the eval parameters.
<img width="615" alt="微信图片_20230708185653" src="https://github.com/bdi-lab/HyNT/assets/91859784/a7e01d21-1f99-4808-99a7-ead91e89e91d">

**Comment by jaejunlee714** [comment]
Hi, 
Thanks for your interest!
The parameters for training are equal to the parameters for evaluation.
You can just use num_epoch instead of epoch for training.

Sincerely,
Jaejun Lee

**Comment by ZeyuZhu0120** [comment]
Thank you very much for your timely reply. I will run it later~
