### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by ZeyuZhu0120** [bdi-lab/HyNT#2]
Dear authors,
I found that there were no WikiPeople- and WD50K datasets in the project (train, test, valid, total as well as HN-WK). Could you please provide these two data sets? Looking forward to your reply!

**Comment by jaejunlee714** [comment]
Hi,
Thanks for your interest.
You can find WikiPeople- and WD50K in data_normalized folder.

Sincerely,
Jaejun Lee

**Comment by ZeyuZhu0120** [comment]
> Hi, Thanks for your interest. You can find WikiPeople- and WD50K in data_normalized folder.
> 
> Sincerely, Jaejun Lee

Oh, I'm so sorry! I didn't get a good look at those two data sets. It's my fault. Thank you for your reminder and your timely and patient reply!👍
