### ISSUE TITLE
question about the performance of link prediction task result based on your checkpoint

### ISSUE THREAD

**Issue by ohowandanliao** [bdi-lab/HyNT#3]
Dear author, thank you for your great work! 
I'm trying to replicate your work, but the performance I got is quite different from that in your paper. The code and checkpoints I use come from your git. 
Here is the result I got
![image](https://github.com/bdi-lab/HyNT/assets/46982343/16c7fca6-0b18-46b1-9c8d-414255d42945)
![image](https://github.com/bdi-lab/HyNT/assets/46982343/a6a864e7-eab2-412a-a91f-06a958ab8c2d)
I used your code to train the HN-WK data set, but the MRR was still relatively low at 300 epochs. Is there something wrong with my training method?
![image](https://github.com/bdi-lab/HyNT/assets/46982343/188cd6c8-c921-4e38-8b37-2bf48728400f)

**Comment by jaejunlee714** [comment]
Hi, thanks for your interest in our work!
As we updated on the main page of this repository, we found a bug in filter_dict for HNKGs recently, and we're currently working on tuning HyNT with the fixed filter_dict. We will release the full updated results and the checkpoints as soon as possible. Our Tentative results on HN-WK with limited parameter tuning is:
Link Prediction on the Primary Triplets in HN-WK (Updated)
MRR: 0.3025 / Hit10: 0.5037 / Hit3: 0.3214 / Hit1: 0.2075

Link Prediction on All Entities of the Hyper-Relational Facts in HN-WK (Updated)
MRR: 0.3234 / Hit10: 0.5216 / Hit3: 0.3439 / Hit1: 0.2294

Sorry for confusion.
