### ISSUE TITLE
The results of the experiment are not correct

### ISSUE THREAD

**Issue by lainanhui** [bdi-lab/HyNT#4]
Hi, I ran three datasets, HN-WK, HN-YG, HN-FB-S,but the results of the runs don't match with the experimental results you provided in your paper, I'd like to ask what's going on, and is it convenient to see your experimental results?
![1714392063664](https://github.com/bdi-lab/HyNT/assets/85324054/323854f0-d099-49f6-af88-9b7b763600d6)
![HN-YG](https://github.com/bdi-lab/HyNT/assets/85324054/22a4f22b-061f-4312-8261-bc3a0af29096)
![HN-WK](https://github.com/bdi-lab/HyNT/assets/85324054/7c58dad5-7cf7-489d-bcac-6b2a741b934d)

**Comment by lainanhui** [comment]
Looking forward to your reply and good luck with your research!

**Comment by jaejunlee714** [comment]
Hi, thanks for your interest in our paper. 
As we have wrote in our README.txt, we found and fixed a bug in filter_dict in January. The link prediction results on HN-KGs in the paper (i.e., HN-WK, HN-YG, HN-FB-S) need to be updated. We will release the updated results and the checkpoints as soon as possible.
Sorry for inconvenience.

Best,
Jaejun Lee

**Comment by lainanhui** [comment]
Thank you dear author and for the work you have done. I previously understood readme.md to mean that only one dataset needs to be updated while the other two do not, and apologize to you for my misunderstanding. I am very much looking forward to the results of the new dataset that will be updated afterwards and wish you all the best!

> Hi, thanks for your interest in our paper. As we have wrote in our README.txt, we found and fixed a bug in filter_dict in January. The link prediction results on HN-KGs in the paper (i.e., HN-WK, HN-YG, HN-FB-S) need to be updated. We will release the updated results and the checkpoints as soon as possible. Sorry for inconvenience.
> 
> Best, Jaejun Lee

**Comment by jaejunlee714** [comment]
Thanks for your understanding. I'll close the issue. Wish you a good luck with your research!
