### ISSUE TITLE
Baseline Reproduction

### ISSUE THREAD

**Issue by wjj0122** [bdi-lab/HyNT#6]
Thank you for your excellent work!
I have encountered some problems with the baseline reproduction, so I sincerely hope to receive your help. I noticed that you reproduced many baselines, including GRAN. I also want to reproduce these baselines, but I have found that the source code of GRAN cannot run anymore because the Paddle Paddle 1.5.0 package has been deleted. Therefore, I would like to sincerely ask how you reproduced GRAN, whether you used the code provided by them or rebuilt it yourself, and what the environment is. I would greatly appreciate your reply!

**Comment by ChanyoungChung** [comment]
Hi, thanks for your interest.

We used the original implementation of GRAN provided by the authors, with minimal modifications to enable numeric value prediction. To reproduce GRAN, we used `paddlepaddle-gpu 1.5.0.post107`, which was available at that moment.

Best regards,
Chanyoung Chung

**Comment by wjj0122** [comment]
Thank you for your reply
